### PR TITLE
Final fix from GSoC 2016

### PR DESCRIPTION
**Pull request by jgorzny**
One fix appears to be missing from the main repository, this adds it.

### CODE REVIEW

**Comment by jgorzny** [comment]
I merged conflicts, but it introduced several errors for build - all relating to 'akka'. Presumably this is just a package I am missing. Should I have it external to Skeptik, or should it be somewhere in Skeptik (and I am missing it)? Let me know if you are you not experiencing these errors, or how I can fix them if you know how.

**Comment by Zahnentferner** [comment]
@itegulov included the akka package in "build.sbt". Therefore, you shouldn't be experiencing errors relating to it.

Could you copy-paste your error messages here?

**Comment by jgorzny** [comment]
The errors were simply that certain classes could not be found. The built.sbt was correct (and included akka). It was surprising that Eclipse (which I am using to build the project) did not raise any errors about not being able to find that package (I would have expected it to consult that file). After adding the akka project as an external library in my eclipse project, the akka-related errors disappeared.

After that, a few other errors relating to the test files for UnifyingResolution was found - but it was only a missing import statement causing these issues. The last commit adds this import statement.

I now have no build errors in my project.

**Comment by Zahnentferner** [comment]
> The errors were simply that certain classes could not be found. The built.sbt was correct (and included akka). It was surprising that Eclipse (which I am using to build the project) did not raise any errors about not being able to find that package (I would have expected it to consult that file). After adding the akka project as an external library in my eclipse project, the akka-related errors disappeared.

When the "build.sbt" file changes, you must first regenerate the eclipse project configuration, by running `$ sbt` and then `> eclipse`; and then reload/refresh the project within the Eclipse IDE.

**Comment by jgorzny** [comment]
Excellent, thanks!

**Pull request merged**
